import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import "./globals.css";
import ThemeWrapper from "./components/ThemeWrapper";
import Header from "./components/Header";
import { Inter } from "next/font/google"

const inter = Inter({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <AppRouterCacheProvider>
          <ThemeWrapper>
              <Header />
              {children}
          </ThemeWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
